version: 2.1

orbs:
  android: circleci/android@3.0.2
  flutter-orb: circleci/flutter@2.0.4

jobs:
  integration_test_android:
    executor:
      name: android/android_machine
      resource_class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - flutter-orb/install_sdk_and_pub:
          version: 3.27.1
      - run:
          name: Set JDK 17
          command: |
            flutter config --jdk-dir=/usr/lib/jvm/java-17-openjdk-amd64
      - android/create_avd:
          avd_name: flutter
          install: true
          system_image: system-images;android-35;default;x86_64
      - android/start_emulator:
          avd_name: flutter
          no_window: true
          post_emulator_launch_assemble_command: flutter emulators
          # flutter drive -d emulator-5554 --driver=test_driver/integration_test.dart --target=integration_test/timer_test.dart
          # restore-gradle-cache-find-args: ./android -name 'build.gradle'
      - android/run_tests:
          test_command: flutter drive -d emulator-5554 --driver=test_driver/integration_test.dart --target=integration_test/timer_test.dart
      - store_artifacts:
          path: test

workflows:
  integration-test-workflow:
    jobs:
      - integration_test_android