name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:            
        - label: I made sure that the issue I am raising doesn't already exist
          required: true
  - type: textarea
    id: current-bug
    attributes:
      label: Current behaviour
      placeholder: Describe the bug in detail. Please be as specific as possible so the issue can be fixed.
    validations:
      required: true
  - type: textarea
    id: expected-bug
    attributes:
      label: Expected behaviour
      placeholder: What was the expected behaviour?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: |
        Please provide a clear set of steps to reproduce the bug. If relevant, please export the effected timer and upload the exported timer file.
      value: |
        1. Create a timer with 30 seconds work, 10 seconds rest, and 3 active intervals...
        2. ... <!-- describe steps to demonstrate bug -->
        3. ... <!-- for example "Tap on X and see a crash" -->
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Affected OS
      description: What OS are you seeing the problem on?
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: textarea
    id: device-details
    attributes:
      label: device details
      description: If relevant, what exact device(s) or operating system do you use?
      placeholder: |
        * Platform 1: iOS 16.3, Apple iPhone 12
    validations:
      required: false
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: In which OpenHIIT version does the issue occur?
      placeholder: 1.5.0
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots or video recordings to help explain your problem. This is totally optional. 
        You can upload them directly on GitHub. Beware that video file size is limited to 10MB.
      placeholder: Drop screenshots here.
    validations:
      required: false
  - type: textarea
    id: more-info
    attributes:
      label: Related issues / more information
      description: |
        Anything else that might be relevant to the issue?
      placeholder: |
        Related: #123, #456
    validations:
      required: false
  - type: dropdown
    id: working-pull-request
    attributes:
      label: Working on PR
      description: Are you interested in working on a PR for this?
      multiple: false
      options:
        - nope
        - yep
    validations:
      required: true