name: Other
description: Not a bug or feature request? Use this template to file an issue.
labels: ["question"]
body:
  - type: checkboxes
    id: checklist-1
    attributes:
      label: Checklist
      options:            
        - label: I made sure that the issue I am raising doesn't already exist
          required: true
  - type: checkboxes
    id: checklist-2
    attributes:
      label: Checklist
      options:            
        - label: I made sure this should not be a bug
          required: true
  - type: checkboxes
    id: checklist-3
    attributes:
      label: Checklist
      options:            
        - label: I made sure this should not be a feature request
          required: true
  - type: textarea
    id: current-bug
    attributes:
      label: Description
      placeholder: What is it?
    validations:
      required: true
  - type: dropdown
    id: working-pull-request
    attributes:
      label: Working on PR
      description: Are you interested in working on a PR for this?
      multiple: false
      options:
        - nope
        - yep
    validations:
      required: true
